[smtp]
server = "smtp.gmail.com"  # or your school SMTP server
port = 587
sender = "kirkman4george@gmail.com"  # your actual Gmail or school email
password = "12345678"  # NOT your normal Gmail password â€” see below
